/*
 * This file is generated by jOOQ.
 */
package com.example.demo.db.keys


import com.example.demo.db.tables.OrderFiscal
import com.example.demo.db.tables.records.OrderFiscalRecord

import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val ORDER_FISCAL_PKEY: UniqueKey<OrderFiscalRecord> = Internal.createUniqueKey(OrderFiscal.ORDER_FISCAL, DSL.name("order_fiscal_pkey"), arrayOf(OrderFiscal.ORDER_FISCAL.ID), true)
