/*
 * This file is generated by jOOQ.
 */
package com.example.demo.db.tables.references


import com.example.demo.db.tables.ShipOrder



/**
 * The table <code>state_service.ship_order</code>.
 */
val SHIP_ORDER = ShipOrder.SHIP_ORDER
