/*
 * This file is generated by jOOQ.
 */
package com.example.demo.db.tables.pojos


import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class SagaStepError(
    var id: Int? = null, 
    var sagaId: Int? = null, 
    var sagaStepId: Int? = null, 
    var triesCounter: Int? = null, 
    var description: String? = null, 
    var insertedAt: LocalDateTime? = null
): Serializable {


    override fun toString(): String {
        val sb = StringBuilder("SagaStepError (")

        sb.append(id)
        sb.append(", ").append(sagaId)
        sb.append(", ").append(sagaStepId)
        sb.append(", ").append(triesCounter)
        sb.append(", ").append(description)
        sb.append(", ").append(insertedAt)

        sb.append(")")
        return sb.toString()
    }
}
