/*
 * This file is generated by jOOQ.
 */
package com.example.demo.db.tables.pojos


import com.example.demo.db.enums.CompletionType

import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class Saga(
    var id: Int? = null, 
    var orchestratorAlias: String? = null, 
    var completionState: CompletionType? = null, 
    var triesCount: Int? = null, 
    var nextTriesAt: LocalDateTime? = null, 
    var insertedAt: LocalDateTime? = null, 
    var updatedAt: LocalDateTime? = null
): Serializable {


    override fun toString(): String {
        val sb = StringBuilder("Saga (")

        sb.append(id)
        sb.append(", ").append(orchestratorAlias)
        sb.append(", ").append(completionState)
        sb.append(", ").append(triesCount)
        sb.append(", ").append(nextTriesAt)
        sb.append(", ").append(insertedAt)
        sb.append(", ").append(updatedAt)

        sb.append(")")
        return sb.toString()
    }
}
