/*
 * This file is generated by jOOQ.
 */
package com.example.demo.db.tables.pojos


import com.example.demo.db.enums.StepCompletionType
import com.example.demo.db.enums.TransactionType

import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class SagaStep(
    var id: Int? = null, 
    var sagaId: Int? = null, 
    var stepNumber: Int? = null, 
    var completionState: StepCompletionType? = null, 
    var triesCount: Int? = null, 
    var transactionType: TransactionType? = null, 
    var inputContext: ByteArray? = null, 
    var outputContext: ByteArray? = null, 
    var insertedAt: LocalDateTime? = null, 
    var updatedAt: LocalDateTime? = null
): Serializable {


    override fun toString(): String {
        val sb = StringBuilder("SagaStep (")

        sb.append(id)
        sb.append(", ").append(sagaId)
        sb.append(", ").append(stepNumber)
        sb.append(", ").append(completionState)
        sb.append(", ").append(triesCount)
        sb.append(", ").append(transactionType)
        sb.append(", ").append("[binary...]")
        sb.append(", ").append("[binary...]")
        sb.append(", ").append(insertedAt)
        sb.append(", ").append(updatedAt)

        sb.append(")")
        return sb.toString()
    }
}
