/*
 * This file is generated by jOOQ.
 */
package com.example.demo.db.enums


import com.example.demo.db.OrderFiscalService

import org.jooq.Catalog
import org.jooq.EnumType
import org.jooq.Schema


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
enum class OrderFiscalState(@get:JvmName("literal") val literal: String) : EnumType {
    FISCALIZED_PENDING("FISCALIZED_PENDING"),
    FISCALIZED("FISCALIZED"),
    REJECTED("REJECTED");
    override fun getCatalog(): Catalog? = schema.catalog
    override fun getSchema(): Schema = OrderFiscalService.ORDER_FISCAL_SERVICE
    override fun getName(): String = "order_fiscal_state"
    override fun getLiteral(): String = literal
}
