/*
 * This file is generated by jOOQ.
 */
package com.example.demo.db.tables.pojos


import com.example.demo.db.enums.OrderFiscalState

import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class OrderFiscal(
    var id: Int? = null, 
    var orderId: Int? = null, 
    var state: OrderFiscalState? = null, 
    var insertedAt: LocalDateTime? = null, 
    var updatedAt: LocalDateTime? = null
): Serializable {


    override fun toString(): String {
        val sb = StringBuilder("OrderFiscal (")

        sb.append(id)
        sb.append(", ").append(orderId)
        sb.append(", ").append(state)
        sb.append(", ").append(insertedAt)
        sb.append(", ").append(updatedAt)

        sb.append(")")
        return sb.toString()
    }
}
