/*
 * This file is generated by jOOQ.
 */
package com.example.demo.db.tables


import com.example.demo.db.OrderFiscalService
import com.example.demo.db.enums.OrderFiscalState
import com.example.demo.db.keys.ORDER_FISCAL_PKEY
import com.example.demo.db.tables.records.OrderFiscalRecord

import java.time.LocalDateTime

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row5
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class OrderFiscal(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, OrderFiscalRecord>?,
    aliased: Table<OrderFiscalRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<OrderFiscalRecord>(
    alias,
    OrderFiscalService.ORDER_FISCAL_SERVICE,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>order_fiscal_service.order_fiscal</code>
         */
        val ORDER_FISCAL = OrderFiscal()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<OrderFiscalRecord> = OrderFiscalRecord::class.java

    /**
     * The column <code>order_fiscal_service.order_fiscal.id</code>.
     */
    val ID: TableField<OrderFiscalRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>order_fiscal_service.order_fiscal.order_id</code>.
     */
    val ORDER_ID: TableField<OrderFiscalRecord, Int?> = createField(DSL.name("order_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>order_fiscal_service.order_fiscal.state</code>.
     */
    val STATE: TableField<OrderFiscalRecord, OrderFiscalState?> = createField(DSL.name("state"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(com.example.demo.db.enums.OrderFiscalState::class.java), this, "")

    /**
     * The column <code>order_fiscal_service.order_fiscal.inserted_at</code>.
     */
    val INSERTED_AT: TableField<OrderFiscalRecord, LocalDateTime?> = createField(DSL.name("inserted_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("now()", SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>order_fiscal_service.order_fiscal.updated_at</code>.
     */
    val UPDATED_AT: TableField<OrderFiscalRecord, LocalDateTime?> = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("now()", SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<OrderFiscalRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<OrderFiscalRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>order_fiscal_service.order_fiscal</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>order_fiscal_service.order_fiscal</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>order_fiscal_service.order_fiscal</code> table reference
     */
    constructor(): this(DSL.name("order_fiscal"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, OrderFiscalRecord>): this(Internal.createPathAlias(child, key), child, key, ORDER_FISCAL, null)
    override fun getSchema(): Schema = OrderFiscalService.ORDER_FISCAL_SERVICE
    override fun getIdentity(): Identity<OrderFiscalRecord, Int?> = super.getIdentity() as Identity<OrderFiscalRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<OrderFiscalRecord> = ORDER_FISCAL_PKEY
    override fun getKeys(): List<UniqueKey<OrderFiscalRecord>> = listOf(ORDER_FISCAL_PKEY)
    override fun `as`(alias: String): OrderFiscal = OrderFiscal(DSL.name(alias), this)
    override fun `as`(alias: Name): OrderFiscal = OrderFiscal(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): OrderFiscal = OrderFiscal(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): OrderFiscal = OrderFiscal(name, null)

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row5<Int?, Int?, OrderFiscalState?, LocalDateTime?, LocalDateTime?> = super.fieldsRow() as Row5<Int?, Int?, OrderFiscalState?, LocalDateTime?, LocalDateTime?>
}
