/*
 * This file is generated by jOOQ.
 */
package com.example.demo.db.tables.references


import com.example.demo.db.tables.OrderFiscal



/**
 * The table <code>order_fiscal_service.order_fiscal</code>.
 */
val ORDER_FISCAL = OrderFiscal.ORDER_FISCAL
