/*
 * This file is generated by jOOQ.
 */
package com.example.demo.db


import com.example.demo.db.sequences.ORDER_FISCAL_ID_SEQ
import com.example.demo.db.tables.OrderFiscal

import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Sequence
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class OrderFiscalService : SchemaImpl("order_fiscal_service", DefaultCatalog.DEFAULT_CATALOG) {
    companion object {

        /**
         * The reference instance of <code>order_fiscal_service</code>
         */
        val ORDER_FISCAL_SERVICE = OrderFiscalService()
    }

    /**
     * The table <code>order_fiscal_service.order_fiscal</code>.
     */
    val ORDER_FISCAL get() = OrderFiscal.ORDER_FISCAL

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getSequences(): List<Sequence<*>> = listOf(
        ORDER_FISCAL_ID_SEQ
    )

    override fun getTables(): List<Table<*>> = listOf(
        OrderFiscal.ORDER_FISCAL
    )
}
