/*
 * This file is generated by jOOQ.
 */
package com.example.demo.db.sequences


import com.example.demo.db.OrderFiscalService

import org.jooq.Sequence
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType



/**
 * The sequence <code>order_fiscal_service.order_fiscal_id_seq</code>
 */
val ORDER_FISCAL_ID_SEQ: Sequence<Int> = Internal.createSequence("order_fiscal_id_seq", OrderFiscalService.ORDER_FISCAL_SERVICE, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null)
