/*
 * This file is generated by jOOQ.
 */
package com.example.demo.db.tables.references


import com.example.demo.db.tables.Saga
import com.example.demo.db.tables.SagaStep
import com.example.demo.db.tables.SagaStepError



/**
 * The table <code>saga_scheme.saga</code>.
 */
val SAGA = Saga.SAGA

/**
 * The table <code>saga_scheme.saga_step</code>.
 */
val SAGA_STEP = SagaStep.SAGA_STEP

/**
 * The table <code>saga_scheme.saga_step_error</code>.
 */
val SAGA_STEP_ERROR = SagaStepError.SAGA_STEP_ERROR
