/*
 * This file is generated by jOOQ.
 */
package com.example.demo.db.indexes


import com.example.demo.db.tables.SagaStep

import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val SAGA_ID_AND_STEP_NUMBER_UINDEX: Index = Internal.createIndex(DSL.name("saga_id_and_step_number_uindex"), SagaStep.SAGA_STEP, arrayOf(SagaStep.SAGA_STEP.SAGA_ID, SagaStep.SAGA_STEP.STEP_NUMBER), true)
