/*
 * This file is generated by jOOQ.
 */
package com.example.demo.db.enums


import com.example.demo.db.OrderService

import org.jooq.Catalog
import org.jooq.EnumType
import org.jooq.Schema


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
enum class OrderState(@get:JvmName("literal") val literal: String) : EnumType {
    CREATED_PENDING("CREATED_PENDING"),
    CREATED("CREATED"),
    REJECTED("REJECTED");
    override fun getCatalog(): Catalog? = schema.catalog
    override fun getSchema(): Schema = OrderService.ORDER_SERVICE
    override fun getName(): String = "order_state"
    override fun getLiteral(): String = literal
}
