/*
 * This file is generated by jOOQ.
 */
package com.example.demo.db.keys


import com.example.demo.db.tables.ShipOrder
import com.example.demo.db.tables.records.ShipOrderRecord

import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val SHIP_ORDER_PKEY: UniqueKey<ShipOrderRecord> = Internal.createUniqueKey(ShipOrder.SHIP_ORDER, DSL.name("ship_order_pkey"), arrayOf(ShipOrder.SHIP_ORDER.ID), true)
