/*
 * This file is generated by jOOQ.
 */
package com.example.demo.db.enums


import com.example.demo.db.Public

import org.jooq.Catalog
import org.jooq.EnumType
import org.jooq.Schema


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
enum class CompletionType(@get:JvmName("literal") val literal: String) : EnumType {
    IN_PROGRESS("IN_PROGRESS"),
    COMPLETE("COMPLETE"),
    ERROR("ERROR");
    override fun getCatalog(): Catalog? = schema.catalog
    override fun getSchema(): Schema = Public.PUBLIC
    override fun getName(): String = "completion_type"
    override fun getLiteral(): String = literal
}
