/*
 * This file is generated by jOOQ.
 */
package com.example.demo.db.enums


import com.example.demo.db.Public

import org.jooq.Catalog
import org.jooq.EnumType
import org.jooq.Schema


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
enum class StepCompletionType(@get:JvmName("literal") val literal: String) : EnumType {
    WAIT("WAIT"),
    SUCCESS("SUCCESS"),
    ERROR("ERROR"),
    ROLLBACK("ROLLBACK");
    override fun getCatalog(): Catalog? = schema.catalog
    override fun getSchema(): Schema = Public.PUBLIC
    override fun getName(): String = "step_completion_type"
    override fun getLiteral(): String = literal
}
